### ISSUE TITLE
Integración Completa sMaker

### ISSUE THREAD

**Issue by jmcasimar** [Ecolistico/GrowGreens#14]
- [x] Diseño y Funcionamiento del solutionMaker @santiagoSaracho
- [x] Añadir condiciones try/except para que el uso del microcontrolador sMaker sea opcional. Aprovechar para hacer lo mismo para motorsGrower. Omitir en _growMaster.py_ todas las funciones que manden a llamar estos objetos, cuidando que no se cicle el programa.
- [x] Integrar al código las nuevas funciones entre ellas pwm para el control de los servos.
- [x] Desconectar el sMaker y verificar sensores ph/ec. EC no está funcionando.
- [x] Probar funcionamiento e integración con el resto del sistema

**Comment by jmcasimar** [comment]
El sistema esta preparado sólo queda pendiente la indicación de @SantiSarGon para realizar las pruebas de funcionamiento cuando las bombas peristalticas estén al 100%

**Comment by SantiSarGon** [comment]
- [ ] Actualizar código en GitHub
- [ ] Integrar a GrowGreens
- [ ] Realizar pruebas de funcionamiento

**Comment by jmcasimar** [comment]
La versión actual de diseño actual se está modificando y quedará obsoleta a la brevedad. Por lo tanto, todas las actividades que hubiesen quedado pendiente se cancelan en automático.
