### ISSUE TITLE
Missing config.csv file stops ability to run the GUI code

### ISSUE THREAD

**Issue by PySimpleGUI** [Ecolistico/GrowGreens#36]
**Describe the bug**

Have been trying to run the GUI files to see what your GUI looks like, but I'm unable to run either of them due to a missing file config.csv.  I don't see it anywhere on GitHub and am unsure what goes in it.  Can you upload one so that the code will run straight from the repo?

**To Reproduce**
1. Download ZIP
2. Run either of the gui.py files

**Expected behavior**
A GUI is shown

**Screenshots**

```
C:\Python\Anaconda3\python.exe E:/DownloadsE/GrowGreens-master/Python/Master/src/gui.py
Traceback (most recent call last):
  File "E:/DownloadsE/GrowGreens-master/Python/Master/src/gui.py", line 571, in <module>
    main()
  File "E:/DownloadsE/GrowGreens-master/Python/Master/src/gui.py", line 566, in main
    gui.begin()
  File "E:/DownloadsE/GrowGreens-master/Python/Master/src/gui.py", line 263, in begin
    with open(self.filename, "r") as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'config.csv'
```

**Desktop (please complete the following information):**

Windows 10

**Comment by jmcasimar** [comment]
Excuse me for the delay. 

The code has been tested in python 3.5 and 3.8, and it does not work for python 2. To run the GUI you need to uncomment these lines in the [gui.py](https://github.com/Ecolistico/GrowGreens/blob/master/Python/Master/src/gui.py):

```
# Debug
def main():
    gui = GUI()
    gui.begin()
    while gui.isOpen:
        gui.run()

if __name__ == '__main__':
    main()
```

The reason you do not have config.csv file is that is expected each computer has its own parameters, so we do not track this file in the repository, I am going to consider add an exampleConfig.csv file and explain how to use it. In the meantime I attach an example file [config.zip](https://github.com/Ecolistico/GrowGreens/files/4517374/config.zip), you have to unzip this file and save it in Python/Master/src/ the expected output is this:

![Captura](https://user-images.githubusercontent.com/50505995/80005742-a01f1900-8489-11ea-883e-0dafce465bd7.PNG)

**Comment by PySimpleGUI** [comment]
How about creating one for the user if it's not present?  That's what I do for my "settings" files.  There's a default setting that is in the code and written when no settings file is found.

**Comment by jmcasimar** [comment]
Ok, that approach sounds better. I'm working on it.

**Comment by jmcasimar** [comment]
This issue was already solved, please check it out.

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/80658145-51f2b280-8a53-11ea-91e8-b57062ddf01d.png)


Success this time around.  I had forgotten how I was trying to run it until I looked at the original text in this issue.  I can't run setup as I'm on Windows and it tries to run a bunch of shell commands.  

But I figured out that I just needed to run `gui.py` again and this time it worked!  It's a great looking window.  I like the buttons and graphics you used.  I'm not sure how you did some of the things you did like the green rectangular box on the right side.  I'm sure there are some interesting things in your code that I'll learn from.

![image](https://user-images.githubusercontent.com/46163555/80658312-cdecfa80-8a53-11ea-98ed-ec89a710135b.png)

Ooooooooo...... I just took a minute to poke around a little and was confused seeing a button element with a `maxsize` parameter.  I was wondering how on earth I would have forgotten about that parameter, and then I realized it's a User Defined Element.  :-)    NIcely done!  

Also great to see you have some commented out lines in your layout.  It shows some things you've been experimenting with, trying out.  I do this too and mentioned it in one of the new videos.  It's the only time I've brought it up before and I think you're the first person I've seen that's figured out you can do this.

Even if you don't put instructions in your readme.md file, it would be great to see a screenshot in there.  You clearly spent a lot of time on this GUI and I know people love to see screenshots.  

To add a screenshot to your GitHub's page, all you have to do is copy and paste a screenshot into a GitHub issue, just like I have, and then take the code the GitHub generates and paste it into your readme.md file.  For example, when I pasted the screenshot into this Issue, it added this bit of code:

```
![image](https://user-images.githubusercontent.com/46163555/80658145-51f2b280-8a53-11ea-91e8-b57062ddf01d.png)
```

If you paste that code into the readme.md file, then it will embed the image and show it on your GitHub's main page.

It's so rare for Python programs to have GUIs so I encourage everyone that makes one to show them off.  Show the world what's possible.  You may very well inspire someone else.

**Comment by jmcasimar** [comment]
I happy to hear that everything worked as expected.

Actually the idea of integrate a GUI to the source code is as old as the repository. However we spent the majority of the time making backends developments and all the options to develop a GUI take us too much time.

When we discover [PySimpleGUI](https://github.com/PySimpleGUI/PySimpleGUI) it was possible to develop pretty fast the solution that we need and integrate it to the rest of the project. In that sense, we have to say thank you, without your work it couldn´t be possible make a GUI.

We are conscious that it missed a lot of documentation in the repository, but meanwhile I´m going to add the screnshoot.
